

name: Terraform

on:
  push:
    paths:
      - 'infrastructure/**'
  workflow_dispatch:

jobs:
  Plan:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_KEY}}
      TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME}}
      TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID}}
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_TOKEN}}
      TF_VAR_project_name: "portfolio"
      TF_VAR_arm_subscription_id: ${{secrets.ARM_SUBSCRIPTION_ID}}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.5
      
      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure
      
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infrastructure

  Apply:
    runs-on: ubuntu-latest
    needs: Plan
    environment: production
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_KEY}}
      TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME}}
      TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID}}
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_TOKEN}}
      TF_VAR_project_name: "portfolio"
      TF_VAR_arm_subscription_id: ${{secrets.ARM_SUBSCRIPTION_ID}}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.5
      
      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure
      
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infrastructure